# Generated by Django 4.0.1 on 2022-01-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('Name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=12)),
                ('regfruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frexco.region[name]')),
            ],
        ),
    ]
